// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gguedes14/mundo-invest/internal/domain (interfaces: ClientDomain)
//
// Generated by this command:
//
//	mockgen github.com/gguedes14/mundo-invest/internal/domain ClientDomain
//

// Package mock_domain is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gguedes14/mundo-invest/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClientDomain is a mock of ClientDomain interface.
type MockClientDomain struct {
	ctrl     *gomock.Controller
	recorder *MockClientDomainMockRecorder
	isgomock struct{}
}

// MockClientDomainMockRecorder is the mock recorder for MockClientDomain.
type MockClientDomainMockRecorder struct {
	mock *MockClientDomain
}

// NewMockClientDomain creates a new mock instance.
func NewMockClientDomain(ctrl *gomock.Controller) *MockClientDomain {
	mock := &MockClientDomain{ctrl: ctrl}
	mock.recorder = &MockClientDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientDomain) EXPECT() *MockClientDomainMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientDomain) CreateClient(ctx context.Context, client *domain.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientDomainMockRecorder) CreateClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientDomain)(nil).CreateClient), ctx, client)
}
