// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/eventDomain.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/eventDomain.go -destination=internal/mocks/event_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gguedes14/mundo-invest/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventDomain is a mock of EventDomain interface.
type MockEventDomain struct {
	ctrl     *gomock.Controller
	recorder *MockEventDomainMockRecorder
	isgomock struct{}
}

// MockEventDomainMockRecorder is the mock recorder for MockEventDomain.
type MockEventDomainMockRecorder struct {
	mock *MockEventDomain
}

// NewMockEventDomain creates a new mock instance.
func NewMockEventDomain(ctrl *gomock.Controller) *MockEventDomain {
	mock := &MockEventDomain{ctrl: ctrl}
	mock.recorder = &MockEventDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDomain) EXPECT() *MockEventDomainMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockEventDomain) CreateEvent(ctx context.Context, event *domain.Events) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventDomainMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEventDomain)(nil).CreateEvent), ctx, event)
}
